version: '3'
services:
  flask:
    build: .
    ports: 
        - 5000:5000
    volumes: 
      - .:/usr/src/app
    tty: true
    command: >
      sh -c '
      flask run --host 0.0.0.0 --port 5000
      '
